---
title: "04_Defining_exceptions"
output: html_document
---

[Contenido](../Contents.Rmd) \| [Anterior (4.3 Métodos especiales)](03_Special_methods.Rmd) \| [Próximo (5. Funcionamiento interno de los objetos de Python)](../05_Modelo_de_objetos/00_Descripción_general.Rmd)

### 4.4 Definición de excepciones

Las excepciones definidas por el usuario se definen por clases.

```python
class NetworkError(Exception):
    pass
    ```

**Las excepciones siempre heredan de `Exception`.**

Normalmente son clases vacías. Utilice `pass` para el cuerpo. También puede crear una jerarquía de sus excepciones.

```python
class AuthenticationError(NetworkError):
    pass

class ProtocolError(NetworkError):
    pass
```

#### Ejercicios

##### Ejercicio 4.11: Definición de una excepción personalizada

A menudo, es una buena práctica que las bibliotecas definan sus propias excepciones.

Esto facilita la distinción entre las excepciones de Python generadas en respuesta a errores de programación comunes y las excepciones generadas intencionalmente por una biblioteca para señalar un problema de uso específico.

Modifique la función `create_formatter()` del último ejercicio para que genere una excepción `FormatError` personalizada cuando el usuario proporcione un nombre de formato incorrecto.

Por ejemplo:

```python
>>> from tableformat import create_formatter
>>> formatter = create_formatter('xls')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "tableformat.py", line 71, in create_formatter
    raise FormatError('Unknown table format %s' % name)
FormatError: Unknown table format xls
>>>
```

[Contenido](../Contents.Rmd) \| [Anterior (4.3 Métodos especiales)](03_Special_methods.Rmd) \| [Próximo (5. Funcionamiento interno de los objetos de Python)](../05_Modelo_de_objetos/00_Descripción_general.Rmd)